# Generated by Django 5.1 on 2024-11-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('alumni_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('story_title', models.CharField(max_length=255)),
                ('story_content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
