# Generated by Django 5.1 on 2024-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='alumni_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
