# Generated by Django 5.1 on 2024-11-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0002_alter_successstory_alumni_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='visibility',
        ),
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images/'),
        ),
    ]
