# Generated by Django 5.1 on 2024-11-11 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0003_remove_successstory_image_url_and_more'),
        ('user', '0003_delete_successstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='alumni_id',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='company_id',
        ),
        migrations.AddField(
            model_name='successstory',
            name='alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='user.alumni'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
