# Generated by Django 5.1 on 2024-11-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0005_remove_successstory_alumni_successstory_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstory',
            name='company',
        ),
    ]
