# Generated by Django 5.1 on 2024-11-11 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0006_remove_successstory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
