# Generated by Django 5.1 on 2024-11-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_companydetails_companyreview_successstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='alumni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
