# Generated by Django 5.1 on 2024-11-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_companydetails_companyreview_successstory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessStory',
        ),
    ]
