# Generated by Django 5.1 on 2024-11-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_companydetails_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreview',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
        migrations.DeleteModel(
            name='CompanyReview',
        ),
    ]
