# Generated by Django 5.1 on 2024-11-08 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniDetails',
            fields=[
                ('alumni_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_company_id', models.IntegerField(blank=True, null=True)),
                ('graduation_year', models.IntegerField()),
                ('current_company', models.CharField(max_length=100)),
                ('current_position', models.CharField(max_length=100)),
                ('linkedIn_profile', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
