# Generated by Django 5.1 on 2024-11-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnidetails',
            name='alumni_id',
        ),
        migrations.RemoveField(
            model_name='alumnidetails',
            name='current_company_id',
        ),
        migrations.AddField(
            model_name='alumnidetails',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
