# Generated by Django 5.1 on 2024-11-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenti', '0003_studentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='role_type',
            field=models.CharField(max_length=20),
        ),
    ]
