# Generated by Django 5.1 on 2024-11-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('headquarters', models.CharField(blank=True, max_length=255, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('core_products_services', models.TextField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('recruitment_process', models.TextField(blank=True, null=True)),
                ('common_roles', models.TextField(blank=True, null=True)),
                ('global_presence', models.BooleanField(default=False)),
                ('college_visited', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='company_profiles/')),
                ('profile_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
