# Generated by Django 5.1 on 2024-11-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lib', '0002_alter_companydetails_profile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.IntegerField(blank=True, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('review_title', models.CharField(max_length=255)),
                ('review_content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='profile_url',
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
