# Generated by Django 5.1 on 2024-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lib', '0003_companyreview_remove_companydetails_profile_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_profiles/'),
        ),
    ]
