# Generated by Django 5.1 on 2024-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lib', '0004_alter_companydetails_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
