# Generated by Django 5.1 on 2024-11-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lib', '0005_companydetails_country'),
        ('user', '0004_remove_companyreview_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='company_lib.companydetails'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.user'),
        ),
    ]
