# Generated by Django 5.1 on 2024-11-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_lib', '0007_alter_companyreview_company_alter_companyreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='company_lib.companydetails'),
        ),
    ]
